repository: https://github.com/mfazrinizar/flutter_secure_dotenv
name: flutter_secure_dotenv
description: Package to securely manage environment variables and perform AES encryption/decryption in Flutter and Dart.
version: 2.0.0

environment:
  sdk: ^3.8.0

dependencies:
  pointycastle: ^4.0.0

dev_dependencies:
  lints: ^6.1.0
  test: ^1.29.0
